[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pocm_vault_mining = "2oJ68QPvNqvdegxPczqGYz7bmTyBSW9D6ZYs4w1HSpL9"

[programs.testnet]
pocm_vault_mining = "2oJ68QPvNqvdegxPczqGYz7bmTyBSW9D6ZYs4w1HSpL9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.testnet.x1.xyz"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 60000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 200000 tests/**/*.ts"
